import { NgModule } from "@angular/core"
import {
    AlignmentModule,
    AlignmentToolModule,
    BaseModule,
    BasicEditorModule as Editor,
    BlockquoteModule,
    BlockTypeModule,
    CodeModule,
    CodeToolModule,
    DocModule,
    EditorToolbarModule,
    EmphasisToolModule,
    HardBreakModule,
    HeadingModule,
    HeadingToolModule,
    HorizontalRuleModule,
    LinkModule,
    LinkToolModule,
    ParagraphModule,
    StrikeToolModule,
    StrongToolModule,
    SubscriptToolModule,
    SuperscriptToolModule,
    TextFormattingModule,
    TextModule,
    UnderlineToolModule,
} from "@zodiac-ui/editor"
import { BasicEditorComponent } from "./basic-editor.component"

@NgModule({
    imports: [
        Editor,
        EditorToolbarModule,
        BaseModule,
        DocModule,
        ParagraphModule,
        TextModule,
        LinkModule,
        HeadingModule,
        BlockquoteModule,
        AlignmentModule,
        HardBreakModule,
        BlockTypeModule,
        CodeModule.configure({
            modeURL: "assets/mode/%N/%N.js",
            extraModes: [
                {
                    name: "Angular",
                    mimes: ["text/angular"],
                    alias: ["ng"],
                    mode: "angular",
                },
            ],
        }),
        TextFormattingModule,
        HorizontalRuleModule,
        StrongToolModule,
        AlignmentToolModule,
        EmphasisToolModule,
        UnderlineToolModule,
        SuperscriptToolModule,
        SubscriptToolModule,
        StrikeToolModule,
        CodeToolModule,
        LinkToolModule,
        HeadingToolModule,
    ],
    exports: [BasicEditorComponent],
    declarations: [BasicEditorComponent],
    providers: [],
})
export class BasicEditorModule {}
